// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ArticleUpdate
    {
        /// <summary>
        /// Initializes a new instance of the ArticleUpdate class.
        /// </summary>
        public ArticleUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ArticleUpdate class.
        /// </summary>
        public ArticleUpdate(ArticleUpdateArticle article = default(ArticleUpdateArticle))
        {
            Article = article;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "article")]
        public ArticleUpdateArticle Article { get; set; }

    }
}
