// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Flare tag of the article
    /// </summary>
    public partial class ArticleFlareTag
    {
        /// <summary>
        /// Initializes a new instance of the ArticleFlareTag class.
        /// </summary>
        public ArticleFlareTag()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ArticleFlareTag class.
        /// </summary>
        /// <param name="bgColorHex">Background color (hexadecimal)</param>
        /// <param name="textColorHex">Text color (hexadecimal)</param>
        public ArticleFlareTag(string name = default(string), string bgColorHex = default(string), string textColorHex = default(string))
        {
            Name = name;
            BgColorHex = bgColorHex;
            TextColorHex = textColorHex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets background color (hexadecimal)
        /// </summary>
        [JsonProperty(PropertyName = "bg_color_hex")]
        public string BgColorHex { get; set; }

        /// <summary>
        /// Gets or sets text color (hexadecimal)
        /// </summary>
        [JsonProperty(PropertyName = "text_color_hex")]
        public string TextColorHex { get; set; }

    }
}
