// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ArticleCreateArticle
    {
        /// <summary>
        /// Initializes a new instance of the ArticleCreateArticle class.
        /// </summary>
        public ArticleCreateArticle()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ArticleCreateArticle class.
        /// </summary>
        /// <param name="bodyMarkdown">The body of the article.
        ///
        /// It can contain an optional front matter. For example
        ///
        /// ```markdown
        /// ---
        /// title: Hello, World!
        /// published: true
        /// tags: discuss, help
        /// date: 20190701T10:00Z
        /// series: Hello series
        /// canonical_url: https://example.com/blog/hello
        /// cover_image: article_published_cover_image
        /// ---
        /// ```
        ///
        /// `date`, `series` and `canonical_url` are optional.
        /// `date` is the publication date-time
        /// `series` is the name of the series the article belongs to
        /// `canonical_url` is the canonical URL of the article
        /// `cover_image` is the main image of the article
        ///
        /// *If the markdown contains a front matter, it will take precedence
        /// on the equivalent params given in the payload.*
        /// </param>
        /// <param name="published">True to create a published article, false
        /// otherwise. Defaults to false
        /// </param>
        /// <param name="series">Article series name.
        ///
        /// All articles belonging to the same series need to have the same
        /// name
        /// in this parameter.
        /// </param>
        /// <param name="organizationId">Only users belonging to an
        /// organization can assign the article to it
        /// </param>
        public ArticleCreateArticle(string title = default(string), string bodyMarkdown = default(string), bool? published = default(bool?), string series = default(string), string mainImage = default(string), string canonicalUrl = default(string), string description = default(string), IList<string> tags = default(IList<string>), int? organizationId = default(int?))
        {
            Title = title;
            BodyMarkdown = bodyMarkdown;
            Published = published;
            Series = series;
            MainImage = mainImage;
            CanonicalUrl = canonicalUrl;
            Description = description;
            Tags = tags;
            OrganizationId = organizationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the body of the article.
        ///
        /// It can contain an optional front matter. For example
        ///
        /// ```markdown
        /// ---
        /// title: Hello, World!
        /// published: true
        /// tags: discuss, help
        /// date: 20190701T10:00Z
        /// series: Hello series
        /// canonical_url: https://example.com/blog/hello
        /// cover_image: article_published_cover_image
        /// ---
        /// ```
        ///
        /// `date`, `series` and `canonical_url` are optional.
        /// `date` is the publication date-time
        /// `series` is the name of the series the article belongs to
        /// `canonical_url` is the canonical URL of the article
        /// `cover_image` is the main image of the article
        ///
        /// *If the markdown contains a front matter, it will take precedence
        /// on the equivalent params given in the payload.*
        ///
        /// </summary>
        [JsonProperty(PropertyName = "body_markdown")]
        public string BodyMarkdown { get; set; }

        /// <summary>
        /// Gets or sets true to create a published article, false otherwise.
        /// Defaults to false
        ///
        /// </summary>
        [JsonProperty(PropertyName = "published")]
        public bool? Published { get; set; }

        /// <summary>
        /// Gets or sets article series name.
        ///
        /// All articles belonging to the same series need to have the same
        /// name
        /// in this parameter.
        ///
        /// </summary>
        [JsonProperty(PropertyName = "series")]
        public string Series { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "main_image")]
        public string MainImage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canonical_url")]
        public string CanonicalUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<string> Tags { get; set; }

        /// <summary>
        /// Gets or sets only users belonging to an organization can assign the
        /// article to it
        ///
        /// </summary>
        [JsonProperty(PropertyName = "organization_id")]
        public int? OrganizationId { get; set; }

    }
}
