// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for createArticle operation.
    /// </summary>
    public partial class CreateArticleHeaders
    {
        /// <summary>
        /// Initializes a new instance of the CreateArticleHeaders class.
        /// </summary>
        public CreateArticleHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateArticleHeaders class.
        /// </summary>
        /// <param name="location">The URL of the new article</param>
        /// <param name="retryAfter">The number of seconds to wait until the
        /// next request</param>
        public CreateArticleHeaders(string location = default(string), int? retryAfter = default(int?))
        {
            Location = location;
            RetryAfter = retryAfter;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the URL of the new article
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets the number of seconds to wait until the next request
        /// </summary>
        [JsonProperty(PropertyName = "Retry-After")]
        public int? RetryAfter { get; set; }

    }
}
