// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ListingUpdate
    {
        /// <summary>
        /// Initializes a new instance of the ListingUpdate class.
        /// </summary>
        public ListingUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListingUpdate class.
        /// </summary>
        public ListingUpdate(ListingUpdateListing listing = default(ListingUpdateListing))
        {
            Listing = listing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listing")]
        public ListingUpdateListing Listing { get; set; }

    }
}
