// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ListingCreate
    {
        /// <summary>
        /// Initializes a new instance of the ListingCreate class.
        /// </summary>
        public ListingCreate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListingCreate class.
        /// </summary>
        public ListingCreate(ListingCreateListing listing = default(ListingCreateListing))
        {
            Listing = listing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listing")]
        public ListingCreateListing Listing { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Listing != null)
            {
                Listing.Validate();
            }
        }
    }
}
