// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Organization
    /// </summary>
    public partial class Organization
    {
        /// <summary>
        /// Initializes a new instance of the Organization class.
        /// </summary>
        public Organization()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Organization class.
        /// </summary>
        /// <param name="joinedAt">Date of joining</param>
        /// <param name="profileImage">Profile image (640x640)</param>
        public Organization(string typeOfProperty = default(string), string username = default(string), string name = default(string), string summary = default(string), string twitterUsername = default(string), string githubUsername = default(string), string url = default(string), string location = default(string), string techStack = default(string), string tagLine = default(string), string story = default(string), System.DateTime? joinedAt = default(System.DateTime?), string profileImage = default(string))
        {
            TypeOfProperty = typeOfProperty;
            Username = username;
            Name = name;
            Summary = summary;
            TwitterUsername = twitterUsername;
            GithubUsername = githubUsername;
            Url = url;
            Location = location;
            TechStack = techStack;
            TagLine = tagLine;
            Story = story;
            JoinedAt = joinedAt;
            ProfileImage = profileImage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type_of")]
        public string TypeOfProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "summary")]
        public string Summary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "twitter_username")]
        public string TwitterUsername { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "github_username")]
        public string GithubUsername { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tech_stack")]
        public string TechStack { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag_line")]
        public string TagLine { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "story")]
        public string Story { get; set; }

        /// <summary>
        /// Gets or sets date of joining
        /// </summary>
        [JsonProperty(PropertyName = "joined_at")]
        public System.DateTime? JoinedAt { get; set; }

        /// <summary>
        /// Gets or sets profile image (640x640)
        /// </summary>
        [JsonProperty(PropertyName = "profile_image")]
        public string ProfileImage { get; set; }

    }
}
