// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The organization the resource belongs to
    /// </summary>
    public partial class SharedOrganization
    {
        /// <summary>
        /// Initializes a new instance of the SharedOrganization class.
        /// </summary>
        public SharedOrganization()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SharedOrganization class.
        /// </summary>
        /// <param name="profileImage">Profile image (640x640)</param>
        /// <param name="profileImage90">Profile image (90x90)</param>
        public SharedOrganization(string name = default(string), string username = default(string), string slug = default(string), string profileImage = default(string), string profileImage90 = default(string))
        {
            Name = name;
            Username = username;
            Slug = slug;
            ProfileImage = profileImage;
            ProfileImage90 = profileImage90;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "slug")]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or sets profile image (640x640)
        /// </summary>
        [JsonProperty(PropertyName = "profile_image")]
        public string ProfileImage { get; set; }

        /// <summary>
        /// Gets or sets profile image (90x90)
        /// </summary>
        [JsonProperty(PropertyName = "profile_image_90")]
        public string ProfileImage90 { get; set; }

    }
}
