// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for updateArticle operation.
    /// </summary>
    public partial class UpdateArticleHeaders
    {
        /// <summary>
        /// Initializes a new instance of the UpdateArticleHeaders class.
        /// </summary>
        public UpdateArticleHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateArticleHeaders class.
        /// </summary>
        /// <param name="retryAfter">The number of seconds to wait until the
        /// next request</param>
        public UpdateArticleHeaders(int? retryAfter = default(int?))
        {
            RetryAfter = retryAfter;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the number of seconds to wait until the next request
        /// </summary>
        [JsonProperty(PropertyName = "Retry-After")]
        public int? RetryAfter { get; set; }

    }
}
