// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Aliencube.Forem.DevTo.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Webhook creation payload
    /// </summary>
    public partial class WebhookCreate
    {
        /// <summary>
        /// Initializes a new instance of the WebhookCreate class.
        /// </summary>
        public WebhookCreate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebhookCreate class.
        /// </summary>
        public WebhookCreate(WebhookCreateWebhookEndpoint webhookEndpoint = default(WebhookCreateWebhookEndpoint))
        {
            WebhookEndpoint = webhookEndpoint;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "webhook_endpoint")]
        public WebhookCreateWebhookEndpoint WebhookEndpoint { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (WebhookEndpoint != null)
            {
                WebhookEndpoint.Validate();
            }
        }
    }
}
